### PR TITLE
Adding Archlinux download link

### PR DESCRIPTION
**Pull request by Skatox**
I've create PKGBUILDS for AUR, so Archlinux users can download this fonts from their package manager.

### CODE REVIEW

**Comment by alexgibson** [comment]
The contents/structure of this repo is going to change considerably very soon. Would that break these links?

**Comment by Skatox** [comment]
No, they won't break. I would be checking this repo to update package's internal structure but URL will be the same.
May I suggest folders without spaces in the names? It'll simplify package creation.

**Comment by alexgibson** [comment]
So to keep you links up to date, it requires you to personally check and manually update? (Sorry I'm not familiar with Linux). 

There are some very specific changes coming as we're also going to be hosting these on google fonts. What those will be I can't say just yet.

**Comment by Skatox** [comment]
No, I don't need to change URLs later. Links do not depend on the structure of the repo.

**Comment by alexgibson** [comment]
I wasn't referring to the URLs sorry. So the links in the readme would always guarantee to point to the latest release here in GitHub? Can you explain how that works? I'm hesitant to include these if they may point to what becomes outdated.

**Comment by Skatox** [comment]
Sure, In Archlinux in order to install non-core software you've to install a package from AUR. This "package" is a script that automates the steps to install the software, in this case, the links points to the "script/package" that downloads this repo, search for `otf` and `ttf` files and install them in the correct path. 

If something breaks because structure have change, I (person who created the package/script) need to update the script to support latest change. Other maintaners can update the script too and URL won't change or notify that script has to be updated.

If this repo have tags for versions, I could make the script to work with tags so it never breaks. But after a new version, I've (or other person) to update the script to be compatible with latest version. 

But for all this, url will be the same.

**Comment by alexgibson** [comment]
Ok, I appreciate you making these but it sounds like there's some responsibility for maintenance there in order to keep things up to date. These font files are still evolving considerably, so I don't think it makes sense to include these as official places to download the font right now. Maybe in he future once things have settled.

**Comment by Skatox** [comment]
Sure no problem. Remember the space naming for folders :)

**Comment by alexgibson** [comment]
Will try and keep this in mind, thanks. Closing for now.

**Pull request closed without merging**
